name: Deploy pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy_accenture:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: cd accenture-2023 && npm install

      - name: Install slidev
        run:  cd accenture-2023 && npm i -g @slidev/cli

      - name: Build
        run: cd accenture-2023 && slidev build --base /presentations/accenture-2023

      # Move /accenture-2023/dist to /accenture-2023-dist
      - name: Move dist
        run: mv accenture-2023/dist accenture-2023-dist

      # Remove /accenture-2023
      - name: Remove accenture-2023
        run: rm -rf accenture-2023

      # Move /accenture-2023-dist to /accenture-2023
      - name: Move dist to accenture-2023
        run: mv accenture-2023-dist accenture-2023

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: accenture-2023

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2